MODEL_2D:
  TYPE: "UNetResNet34"
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
#    preprocess_dir: "/datasets_local/datasets_mjaritz/nuscenes_preprocess/preprocess"
#    nuscenes_dir: "/datasets_local/datasets_mjaritz/nuscenes_preprocess"  # only front cam images are needed
    preprocess_dir: "/home/lxf/Workspace/Science/xMUDA/xmuda/xmuda/data/nuscenes/preprocess"
    nuscenes_dir: "/media/lxf/Data/nuScenes"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
#    preprocess_dir: "/datasets_local/datasets_mjaritz/nuscenes_preprocess/preprocess"
#    nuscenes_dir: "/datasets_local/datasets_mjaritz/nuscenes_preprocess"  # only front cam images are needed
    preprocess_dir: "/home/lxf/Workspace/Science/xMUDA/xmuda/xmuda/data/nuscenes/preprocess"
    nuscenes_dir: "/media/lxf/Data/nuScenes"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.47956584, 4.26788384, 5.71114131, 3.80241668, 1.]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
VAL:
  BATCH_SIZE: 32
  PERIOD: 5000
#OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda
OUTPUT_DIR: "outputs/nuscenes/usa_singapore/xmuda"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda

# 这个地方在运行时输出路径前面还有个前缀根目录，根目录定义在xmuda/xmuda/config/xmuda.py中的_C.OUTPUT_DIR